[auth.external.google]
enabled = true
client_id = "839702511871-q094sfunbe900ogttnd9imp4go0llpak.apps.googleusercontent.com"
secret = "env(SUPABASE_AUTH_EXTERNAL_GOOGLE_CLIENT_SECRET)"
skip_nonce_check = false